# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hAjaaaZUsjQYRr_7D6av3whYW2R4cGms
"""

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef,
    confusion_matrix, classification_report
)

st.set_page_config(page_title="Heart Failure Classifier", layout="wide")

st.title("🫀 Heart Failure Prediction Model Evaluator")
st.markdown("Interactive dashboard evaluating multiple classification models on patient test data.")

# Sidebar Configurations
st.sidebar.header("1. Upload Test Dataset")
uploaded_file = st.sidebar.file_uploader("Upload test_data.csv", type=["csv"])

st.sidebar.header("2. Choose Model")
model_option = st.sidebar.selectbox(
    "Select a Model to Evaluate",
    ("Logistic Regression", "Decision Tree", "kNN", "Naive Bayes", "Random Forest")
)

@st.cache_resource
def load_pipeline(name):
    filename = f"model/{name.lower().replace(' ', '_')}.pkl"
    return joblib.load(filename)

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.subheader("Data Preview")
    st.dataframe(data.head(5), use_container_width=True)

    target_col = "HeartDisease"
    if target_col in data.columns:
        X_test = data.drop(columns=[target_col])
        y_test = data[target_col]

        # Load selected model pipeline
        pipeline = load_pipeline(model_option)

        # Predict
        y_pred = pipeline.predict(X_test)
        y_proba = pipeline.predict_proba(X_test)[:, 1]

        # Calculate metrics
        acc = accuracy_score(y_test, y_pred)
        auc = roc_auc_score(y_test, y_proba)
        prec = precision_score(y_test, y_pred)
        rec = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        mcc = matthews_corrcoef(y_test, y_pred)

        # Metric Displays
        st.subheader(f"Performance Metrics: {model_option}")
        m1, m2, m3, m4, m5, m6 = st.columns(6)
        m1.metric("Accuracy", f"{acc:.4f}")
        m2.metric("AUC Score", f"{auc:.4f}")
        m3.metric("Precision", f"{prec:.4f}")
        m4.metric("Recall", f"{rec:.4f}")
        m5.metric("F1 Score", f"{f1:.4f}")
        m6.metric("MCC", f"{mcc:.4f}")

        st.divider()

        # Visualizations
        col_cm, col_rep = st.columns(2)

        with col_cm:
            st.subheader("Confusion Matrix")
            cm = confusion_matrix(y_test, y_pred)
            fig, ax = plt.subplots(figsize=(4, 3))
            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
                        xticklabels=['Normal (0)', 'Heart Disease (1)'],
                        yticklabels=['Normal (0)', 'Heart Disease (1)'])
            ax.set_xlabel("Predicted")
            ax.set_ylabel("Actual")
            st.pyplot(fig)

        with col_rep:
            st.subheader("Classification Report")
            report = classification_report(y_test, y_pred, output_dict=True)
            st.dataframe(pd.DataFrame(report).transpose().style.format(precision=4), use_container_width=True)

    else:
        st.error(f"Target column '{target_col}' not found in the uploaded file.")
else:
    st.info("👈 Please upload `test_data.csv` from the sidebar to begin evaluation.")

!streamlit run app.py &>/content/logs.txt &

!npx localtunnel --port 8501

!curl ://icanhazip.com