# -*- coding: utf-8 -*-
"""Heart_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4fXf7LMyrnQM6dvNvfVDQBbwwjruvwt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

# 1. Load Data
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Heart dataset/heart.csv')

df.shape

df.info()

df.isnull().sum()

df.describe()

df.head()

df.duplicated().sum()

df.select_dtypes(include=np.number).corr()['Cholesterol']

df.select_dtypes(include=np.number).corr()['Age']

sns.pairplot(df)

# 2. Separate Features & Target
X = df.drop(columns=["HeartDisease"])
y = df["HeartDisease"]

# Identify column types
num_features = ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak']
cat_features = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

# 3. Train-Test Split (80-20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Export raw test_data.csv for Streamlit upload
test_df = X_test.copy()
test_df["HeartDisease"] = y_test
test_df.to_csv("test_data.csv", index=False)

# 4. Define Preprocessors
# Preprocessor for models needing scaling (Logistic Regression, kNN, Naive Bayes)
preprocessor_scaled = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_features),
        ('cat', OneHotEncoder(drop='first', sparse_output=False), cat_features)
    ]
)

# Preprocessor for Tree-based models (Decision Tree, Random Forest)
preprocessor_tree = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', num_features),
        ('cat', OneHotEncoder(drop='first', sparse_output=False), cat_features)
    ]
)

# 5. Define Model Pipelines
pipelines = {
    "Logistic Regression": Pipeline([('prep', preprocessor_scaled), ('model', LogisticRegression(max_iter=1000))]),
    "Decision Tree": Pipeline([('prep', preprocessor_tree), ('model', DecisionTreeClassifier(random_state=42))]),
    "kNN": Pipeline([('prep', preprocessor_scaled), ('model', KNeighborsClassifier(n_neighbors=5))]),
    "Naive Bayes": Pipeline([('prep', preprocessor_scaled), ('model', GaussianNB())]),
    "Random Forest": Pipeline([('prep', preprocessor_tree), ('model', RandomForestClassifier(n_estimators=100, random_state=42))])
}

# 6. Train, Evaluate & Save Pipelines
import os
os.makedirs("model", exist_ok=True)

metrics_list = []

for name, pipe in pipelines.items():
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    y_proba = pipe.predict_proba(X_test)[:, 1]

    # Save trained pipeline (handles preprocessing + prediction automatically)
    joblib.dump(pipe, f"model/{name.lower().replace(' ', '_')}.pkl")

    metrics_list.append({
        "ML Model Name": name,
        "Accuracy": round(accuracy_score(y_test, y_pred), 4),
        "AUC": round(roc_auc_score(y_test, y_proba), 4),
        "Precision": round(precision_score(y_test, y_pred), 4),
        "Recall": round(recall_score(y_test, y_pred), 4),
        "F1": round(f1_score(y_test, y_pred), 4),
        "MCC": round(matthews_corrcoef(y_test, y_pred), 4)
    })

comparison_df = pd.DataFrame(metrics_list)
print(comparison_df.to_markdown(index=False))